### ISSUE TITLE
Error on running the CACL SUBNET Application

### ISSUE THREAD

**Issue by gtamilvanan17** [dkraemer/calcsubnet-pwa#2]
Hello @dkraemer , I hope you're doing good.

Today came accross the application, subnet calculator which look like below.
![image](https://github.com/dkraemer/calcsubnet-pwa/assets/121214873/a43a400d-4203-489d-b792-e2b3d4366ade)

And then I got you source code https://github.com/dkraemer/calcsubnet-pwa/.
Then I tried running your code. But I have landed with below errors.
![image](https://github.com/dkraemer/calcsubnet-pwa/assets/121214873/e8d9b494-51d9-4c18-a57b-27a01459b489)

Also the interface seems for two applications are different. Can you please help me in this regards.

Output I have expected:
![image](https://github.com/dkraemer/calcsubnet-pwa/assets/121214873/7cc7c00f-2719-4d88-90ef-f3778152c397)

Output I got:
![image](https://github.com/dkraemer/calcsubnet-pwa/assets/121214873/3b094c5b-e895-4c17-aca0-6477c9ad390e)

Can you please help me in this such case @dkraemer .

Thanks in advance!
Cheers!

**Comment by gtamilvanan17** [comment]
Hello People,

Can anyone please help me in this regards.


Special mentions:
@dkraemer 
@sergiozygmunt

**Comment by dkraemer** [comment]
Hello @gtamilvanan17,

1. My web-app doesn't support different theming options. 
When you **expect** a design like in your screenshots (the black ones) feel free to fork my repo and add the functionality/design you need. 

2. This personal project is from 2021 and works for me as is. I have no intent to update/modify it.
I'll set the repo's status to archived.

Kind regards,
Daniel

**Comment by dkraemer** [comment]
Update: The domain calcsub.net is no longer owned by me (since 2022).
